[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "personalized_learning_coach"
version = "0.0.1"
description = "Hybrid ADK-inspired Personalized Learning Coach (capstone)"
authors = [{name="Vasudha Maddi"}]
requires-python = ">=3.9"
